"""add indexes

Revision ID: 67f0f0c9ae16
Revises: 6133511af65b
Create Date: 2026-07-20 17:26:19.037088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f0f0c9ae16'
down_revision: Union[str, Sequence[str], None] = '6133511af65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blacklist_tokens_expire_at'), 'blacklist_tokens', ['expire_at'], unique=False)
    op.create_index(op.f('ix_blacklist_tokens_token'), 'blacklist_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_comments_team_id'), 'comments', ['team_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_meetings_ends_at'), 'meetings', ['ends_at'], unique=False)
    op.create_index(op.f('ix_meetings_organizer_id'), 'meetings', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_meetings_starts_at'), 'meetings', ['starts_at'], unique=False)
    op.create_index(op.f('ix_meetings_team_id'), 'meetings', ['team_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_meetings_meeting_id'), 'team_meetings', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_team_meetings_team_id'), 'team_meetings', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_meetings_user_id'), 'team_meetings', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_member_team_id'), 'team_member', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_member_user_id'), 'team_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_teams_invite_code'), 'teams', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_invite_code'), table_name='teams')
    op.drop_index(op.f('ix_team_member_user_id'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_team_id'), table_name='team_member')
    op.drop_index(op.f('ix_team_meetings_user_id'), table_name='team_meetings')
    op.drop_index(op.f('ix_team_meetings_team_id'), table_name='team_meetings')
    op.drop_index(op.f('ix_team_meetings_meeting_id'), table_name='team_meetings')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_meetings_team_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_starts_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organizer_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_ends_at'), table_name='meetings')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_team_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_blacklist_tokens_token'), table_name='blacklist_tokens')
    op.drop_index(op.f('ix_blacklist_tokens_expire_at'), table_name='blacklist_tokens')
    # ### end Alembic commands ###
