"""updated BlackListTokens table, added expire_at column

Revision ID: a932684b1716
Revises: b7f773e171c9
Create Date: 2026-07-12 18:51:22.017248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a932684b1716'
down_revision: Union[str, Sequence[str], None] = 'b7f773e171c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('expire_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist_tokens', 'expire_at')
    # ### end Alembic commands ###
