"""Добавлена модель Meeting и связи для нее

Revision ID: df67dd30a522
Revises: 0496e6253b78
Create Date: 2026-07-18 14:44:37.851153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df67dd30a522'
down_revision: Union[str, Sequence[str], None] = '0496e6253b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meetings', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('meetings_user_id_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'users', ['organizer_id'], ['id'])
    op.drop_column('meetings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_user_id_fkey'), 'meetings', 'users', ['user_id'], ['id'])
    op.drop_column('meetings', 'organizer_id')
    op.drop_table('team_meetings')
    # ### end Alembic commands ###
